[[pages]]
name = "Model seletion"
is_section = true
icon = "ğŸ "

[[pages]]
path = "startPage.py"
name = "Model Selection Page"
icon = "ğŸˆï¸"

[[pages]]
path = "localModel.py"
name = "Ask your local AI for help"